server:
  port: 9001
spring:
  application:
    name: service-consumer
    profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://node01:8701/eureka/
BAR-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
system:
    branch: dev
    version: 1.1.5
management:
 endpoints:
   web:
     exposure:
       include: bus-refresh
